### ISSUE TITLE
node-gyp build fails on node 12.4

### ISSUE THREAD

**Issue by ts252** [JoshuaWise/integer#17]
I guess the signature of `node::addon_register_func` has changed. `Init` in integer.cpp needs to take an extra void*. I can make it compile by adding `void* dummy` as a third param.

This happens on both linux and WSL. I'm confused though because runkit has Integer apparently working fine on 12.2

``` 
  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp: In static member function 'static Result Integer::Cast(v8::Local<v8::String>, uint8_t)':
../src/integer.cpp:329:33: error: no matching function for call to 'v8::String::Value::Value(v8::Local<v8::String>&)'
   v8::String::Value utf16(string);
                                 ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/root/.node-gyp/12.4.0/include/node/v8.h:3018:5: note: candidate: 'v8::String::Value::Value(v8::Isolate*, v8::Local<v8::Value>)'
     Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:3018:5: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
../src/integer.cpp: At global scope:
/root/.node-gyp/12.4.0/include/node/node.h:556:43: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.node-gyp/12.4.0/include/node/node.h:590:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/integer.cpp:408:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(integer, Integer::Init);
 ^~~~~~~~~~~
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/root/.node-gyp/12.4.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.node-gyp/12.4.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [integer.target.mk:110: Release/obj.target/integer/src/integer.o] Error 1

```

**Comment by ts252** [comment]
My bad. I failed into upgrade to the a new enough `integer`. confused by multiple binary modules failing to build
